### ISSUE TITLE
Code of FSPM

### ISSUE THREAD

**Issue by pvnieo** [pitbullil/Partial-Correspondence-3D-NNF#1]
Hi,

Congrats on the great paper, and thanks for sharing the code.

I have a question concerning the implementation of FSPM. So basically, the code that you borrowed from Or Litany's repo is only for the robust partial functional maps (RPFM https://github.com/pitbullil/Partial-Correspondence-3D-NNF/blob/master/FSPM/Code/RPFM.m), and not for the fully spectral partial shape matching FSPM, Am I right?

Thank you in advance!

**Comment by pitbullil** [comment]
Yes, I was under the impression RPFM is implementing the FSPM method, and actually couldn't get the code in the main library(FSPM_main.m) to work properly at the time - it failed and I couldn't find the reason.

**Comment by pvnieo** [comment]
Hi @pitbullil 
Thank you for your response!

I just have one question, so, for the other methods you compared against in your paper, did you re-run the code if it's available, or you took the results from the original paper, I'm asking this because in this library there is only the code for FSPM!
Also, in the README, you mentioned that one should download the _test set of SHREC partial_ from the original website, my question is how to evaluate our method on this dataset, since we don't have the ground truth? is it by submitting our results to their [website](https://www.dais.unive.it/~shrec2016/submission.php), in this case, the competition is still open?

Thank you in advance!

**Comment by pitbullil** [comment]
I had taken the table from the previous papers. I had emailed the competition organizers for the ground truth. Last I remember either Emanuelle Rodola or Luca Cosmo had it, email them and I am sure they will cooperate. The competition is closed.

**Comment by pvnieo** [comment]
Hi @pitbullil 

That answer my question, thanks a lot, and good luck for your research!
